name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }} # example: hello.world

        SERVER_FILE: dockerfiles/server/Dockerfile

        IMAGE_TAG: latest
      run: |
        
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:IMAGE_TAG . --file $SERVER_FILE
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:IMAGE_TAG
